title: The Art of Observability
description: >- # this means to ignore newlines until "theme:
  The Art of Observability: SRE Best Practices for System Insights
theme: just-the-docs

url: https://smigielski.github.io/
#url: https://monitoring4sre.com/

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
